# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 721f84fe0cf5833b6bc9921b1694cf5feaea64dfe583283ba28f8b07ad09ee9e8333e8fe5143b2e8d68626231ef53d7443a5de01e78417a507f20a54d27dd289

test:
  secret_key_base: 484e1116bfad72b7cc9e733692d0d45ad3c11837d0ba9d413d26b29e6508078bca36c173f7174a4795e738111ba5777c8f13370559c53581114a7fc75facb280

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
